#- name: Curl HELM
#  shell: curl -LO https://git.io/get_helm.sh

#- name: Chmod file

#- name: Downloading helm get_helm.sh
#  get_url:
#    url: https://git.io/get_helm.sh
#    dest: ~/get_helm.sh
#    mode: '0700'

#- name: Helm Client Installation
#  shell: ./get_helm.sh -v v2.16.1
#  args:
#    chdir: ~/

#- name: Install node using nvm
#  shell: "source /root/.nvm/nvm.sh && nvm install 14.2.0"
#  args:
#    executable: /bin/bash

- name: Install node using nvm
  become: yes
  become_user: root
  shell: >
    /bin/bash -c "source ~/.nvm/nvm.sh && nvm install 14.2.0 && nvm alias default 14.2.0"
    creates=/home/{{ ansible_user_id }}/.nvm/alias

#- name: Debug
#  debug:
#    msg: "test"
